### ISSUE TITLE
Need support for neo4j 4.2.5

### ISSUE THREAD

**Issue by karthikn2510** [philippkueng/node-neo4j#70]
is this module will support with latest version neo4j 4.2.5

**Comment by philippkueng** [comment]
Hi @karthikn2510 thanks for raising the question, I don't think so. I've personally not been using Neo4j for the last couple of years and have not heard of a lot of people using this library. I'd recommend going with https://www.npmjs.com/package/neo4j-driver as it seems to be the official library by Neo4j.

**Comment by karthikn2510** [comment]
Thanks @philippkueng
